### ISSUE TITLE
ReferenceError: WebSocket is not defined

### ISSUE THREAD

**Issue by sameer49** [vitalets/websocket-as-promised#11]
I am getting following error while using this library on nodejs, I am new to this can help me to resolve this.

ReferenceError: WebSocket is not defined
    at Object.createWebSocket (/node_modules/websocket-as-promised/dist/webpack:/src/options.js:34:20)
    at WebSocketAsPromised._createWS (/node_modules/websocket-as-promised/dist/webpack:/src/index.js:291:30)
    at /node_modules/websocket-as-promised/dist/webpack:/src/index.js:205:12
    at PromiseController._callFn (/node_modules/websocket-as-promised/dist/webpack:/node_modules/promise-controller/lib/index.js:187:1)
    at PromiseController.call (/node_modules/websocket-as-promised/dist/webpack:/node_modules/promise-controller/lib/index.js:62:1)
    at WebSocketAsPromised.open (/node_modules/websocket-as-promised/dist/webpack:/src/index.js:203:26)

**Comment by jurajkocan** [comment]
getting same error when i am trying open connection. Any ideas?

```
const wsc = new WebSocketAsPromised(
    "wss://stagesocket.decentgo.com:8090/"            
);
try {
   await wsc.open(); //this will reject promise with error ReferenceError: WebSocket is not defined
   return await wsc.send(data);
} catch (err) {
    console.log("err:", err);
    throw err;
} finally {
    await wsc.close();
}
```

any idea? thx

**Comment by vitalets** [comment]
Hi! 
As Node.js does not have built-in WebSocket constructor (unlike browsers), you need to install 3rd-party package [websocket](https://www.npmjs.com/package/websocket):
```
npm i websocket
```
Then in you file:
```js
const W3CWebSocket = require('websocket').w3cwebsocket;
const WebSocketAsPromised = require('websocket-as-promised');

const wsp = new WebSocketAsPromised(wsUrl, {
  createWebSocket: url => new W3CWebSocket(url)
});

wsp.open()
  .then(() => wsp.send('foo'))
  .then(() => wsp.close())
  .catch(e => console.error(e));
```
